name: Build

on:
  push:
    branches: [ release ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
    - name: Store generated apk file
      uses: actions/upload-artifact@v2
      with:
        name: SaaF-Android
        path: |
            ./app/build/outputs/apk/release/SaaF-Android.apk
            ./app/build/outputs/apk/release/output-metadata.json